# Generated by Django 3.0 on 2020-08-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200821_0821'),
        ('carts', '0002_auto_20200821_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartsitem',
            name='products',
        ),
        migrations.AddField(
            model_name='cartsitem',
            name='product',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
            preserve_default=False,
        ),
    ]
