# Generated by Django 3.0 on 2020-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20200821_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartsitem',
            name='carts',
        ),
        migrations.AddField(
            model_name='carts',
            name='products',
            field=models.ManyToManyField(to='carts.CartsItem'),
        ),
    ]
