# Generated by Django 3.0 on 2020-08-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='product_image',
            new_name='category_image',
        ),
    ]
