# Generated by Django 3.0 on 2020-08-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
