# Generated by Django 3.0 on 2020-08-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Body',
            new_name='body',
        ),
    ]
