# Generated by Django 3.0 on 2020-08-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
