# Generated by Django 3.0 on 2020-08-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='amount',
            new_name='percentage_discount',
        ),
    ]
