# Generated by Django 3.0 on 2020-08-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='percentage_discount',
            field=models.FloatField(default=0),
        ),
    ]
